### ISSUE TITLE
Can't place Captcha 2x on the same Page

### ISSUE THREAD

**Issue by eWert-Online** [die-wegmeister/Wegmeister.Recaptcha#4] opened 2017-10-23 13:10 UTC
Currently you can't place the captcha two times on the same page, because the API-Script `https://www.google.com/recaptcha/api.js` gets loaded twice, resulting in the following Error.

![Captcha API Error](https://user-images.githubusercontent.com/7459510/31890385-3f527054-b803-11e7-8938-d2e3e751bd5f.png)

I currently can think of two possible fixes:

1. Don't implement the API-Script at all and leave it to the user, to implement it (which wouldn't be backwards compatible).
2. Implement a new option under `properties` with which the user can decide if the API-Script gets automatically implemented or not.

Thanks for your work!
Torben

**Comment by Benjamin-K** [comment] 2017-10-23 14:25
Thanks for your feedback. Personally i would prefer to add another option to decide if the api.js file should be included on this element or not. If you disable it on each element you are still able to implement it yourself. If the property is missing/skipped, the api.js file will be included to not break compatibility. 
Additionally i could also add a fix which will prevent the script from being included twice if the property is not set. This would allow editors to add the same form multiple times on a page without breaking reCaptcha.

I will look at this one later.

**Comment by Benjamin-K** [comment] 2018-02-06 09:59
The issue is finally fixed with Version 2.1.1. You possibly need to update your composer.json to get the new version. Version 2.1.0 added support for the new Form Builder (if you use it).

**Closed by Benjamin-K** 2018-02-06 09:59 UTC
